### ISSUE TITLE
Improve website

### ISSUE THREAD

**Issue by prayank23** [bitcoinknots/knots-www#1]
While GUI for Bitcoin Knots looks and works better than Bitcoin Core, the website still needs improvement IMO. I have listed few things below let me know if they make sense:

1. Change header
2. Change features
3. Add one section for API and other docs
4. An option to switch to dark theme
5. One section for videos
6. Share projects that are using Bitcoin Knots

**Comment by luke-jr** [comment]
Having designed the website, I did so in a way that I think looks nice - so I am biased, perhaps too much to judge. :)

I suggest a PR for each proposed change.

(What would the videos be?)

**Comment by prayank23** [comment]
> I suggest a PR for each proposed change.

Sure. Will do today.

> What would the videos be?

Anything related to Bitcoin or Bitcoin Knots which helps a visitor understand more about the implementation, maintainer and contributors. Example: https://youtu.be/CqNEQS80-h4

**Comment by prayank23** [comment]
I tried my best with few PRs which received no response that could help improve website so they are closed.
